#Notes;

#Packages to be installed via apt.
[managers.system]
items = [
    "tmux",
    "newsboat",
    "pulseaudio",
    "pamix",
    "cmus",
    "gpm",
    "gpg",
    "zip",
    "p7zip",
    "flatpak-builder",
    "lshw",
    "wireguard",
    "wireguard-tools",
    "wine",
    "winetricks",
    "btop",
    "htop",
    "ufw",
]
#Disabled pkgs
#opensnitch
#headscale

#Packages to be installed via Soar.
[managers.soar]
items = [
    "fastfetch#github.com.fastfetch-cli.fastfetch:bincache",
    "lazygit#github.com.jesseduffield.lazygit:bincache",
    "micro#github.com.zyedidia.micro:bincache",
]
#Disabled pkgs
