[wine]
version = "steam:Proton-GE Latest"
ntsync = true
dxvk = true
vkd3d = true
fsr = false
graphics_driver = "wayland"

[launch]

[graphics]
mangohud = true

[graphics.gamescope]

[system]
gamemode = true
