" Enable mouse support
set mouse=a

" Colorscheme
colorscheme termschool

" Enable syntax highlighting
syntax on

" Show line numbers
set number

" Wayland clipboard fix (Uncomment if on wayland environment)
autocmd TextYankPost * if (v:event.operator == 'y' || v:event.operator == 'd') | silent! execute 'call system("wl-copy", @")' | endif
nnoremap p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p

" Arrow keys
set whichwrap+=<,>,[,]

" Ctrl+backspace
noremap! <C-h> <C-w>
noremap! <C-BS> <C-w>

"Ctrl+a
map <C-a> <esc>gg0VG<CR>

"Ctrl+Down arrow newline stuff
inoremap <C-Down> <C-o>:call InsertMoveDownOrAddLine()<CR>

function! InsertMoveDownOrAddLine()
  if line('.') == line('$')
    call append(line('.'), '')
    execute "normal! j"
  else
    execute "normal! j"
  endif
endfunction
