" Enable mouse support
set mouse=a

" Colorscheme
colorscheme termschool

" Enable syntax highlighting
syntax on

" Show line numbers
set number

" Ctrl+backspace delete whole word
noremap! <C-BS> <C-w>
noremap! <C-h> <C-w>
