" Enable mouse support
set mouse=a

" Colorscheme
colorscheme termschool

" Enable syntax highlighting
syntax on

" Show line numbers
set number

" Wayland clipboard fix (Uncomment if on wayland environment)
"autocmd TextYankPost * if (v:event.operator == 'y' || v:event.operator == 'd') | silent! execute 'call system("wl-copy", @")' | endif
"nnoremap p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p

" Arrow keys
set whichwrap+=<,>,[,]

map <C-a> <esc>gg0VG<CR>

noremap! <C-h> <C-w>
noremap! <C-BS> <C-w>
