version = 2

[global]
allow_fp16 = true
dll = "~/.config/lsfg-vk/lsfg-vk.dll"
log_level = "info"

[[profile]]
active_in = [ "vkcube", "vkcubepp", "flashplayer_32_sa.exe", "flashplayer_32_", "flashplayer_32" ]
flow_scale = 1.0
multiplier = 2
name = "Flash"
override_present_mode = false
pacing_mode = "vsync"
performance_mode = true
preserve_swapchain_image_count = false
