[library]
card_zoom = 1.0
card_spacing = 10
card_elevation = true
unload_store_pages = true

[tabs]
show_gachas = true
show_epic = true
show_gog = true
show_steam = true

[nav]
width = 164
collapsed = false

[behavior]
minimize_on_launch = false
save_game_logs = false

[display]
scale = 1.0
muted_icons = false
card_flow = "center"

[console_mode]
background = "wave"
active = false

[[categories]]
enabled = true
name = "All Games"
icon = "sports_esports"
kind = "all"
value = ""

[[categories]]
enabled = true
name = "Favourites"
icon = "star"
kind = "favourite"
value = ""

[[categories]]
enabled = true
name = "Recent"
icon = "schedule"
kind = "recent"
value = ""

[[categories]]
enabled = true
name = "Wine"
icon = "wine_bar"
kind = "runner"
value = "wine"

[[categories]]
enabled = true
name = "Native"
icon = "monitor"
kind = "runner"
value = "native"
